@startuml

skinparam actorStyle awesome

"Administrador do sistema" as admin
"Secretaria " as secretaria
"Médico" as medico
"Gerente de estoque" as gerente
"Usuário" as usuario

"CRUD usuários do sistema" as (crud usuario)

"CRUD salas do hospital" as (crud salas)

"Cadastra novos produtos no estoque" as (cadastra produtos)
"Distribui produtos em salas" as (distribui produtos)

"CRUD pacientes" as (crud pacientes)

"Agenda consulta com um paciente" as (agenda consulta)

"Abre uma consulta" as (abre consulta)
"Consome produtos em consulta" as (consome produtos)
"Encerra uma consulta" as (encerra consulta)

"Faz login na aplicação" as (login)

usuario <|-- admin
usuario <|-- secretaria
usuario <|-- medico
usuario <|-- gerente

usuario -up-> (login)

admin -up-> (crud usuario)
(crud usuario) .up.> (login) : include

admin -up-> (crud salas)
(crud salas) .up.> (login) : include

gerente -up-> (cadastra produtos)
gerente -up-> (distribui produtos)
(cadastra produtos) .up.> (login) : include
(distribui produtos) .up.> (login) : include

secretaria -up-> (agenda consulta)
secretaria -up-> (crud pacientes)
(agenda consulta) .up.> (login) : include
(crud pacientes) .up.> (login) : include

medico -up-> (abre consulta) 
medico -up-> (consome produtos)
medico -up-> (encerra consulta) 
(abre consulta) .up.> (login) : include
(consome produtos) .up.> (login) : include
(encerra consulta) .up.> (login) : include

@enduml
