@startuml

skinparam actorStyle awesome

"Administrador do sistema" as admin
Secretaria as secretaria
Médico as medico
"Gerente de estoque" as gerente
"Usuário" as usuario

"Cadastra usuários" as (cadastra usuarios)
"Cadastra salas" as (cadastra salas)

"Cadastra produtos" as (cadastra produtos)
"Distribui produtos em salas" as (distribui produtos)
"Cadastra paciente" as (cadastra paciente)
"Agenda consulta" as (agenda consulta)
"Realiza consulta" as (realiza consulta)
"Utiliza produtos em consulta" as (usa produtos)
"Faz login na aplicação" as (login)

usuario <|-- admin
usuario <|-- secretaria
usuario <|-- medico
usuario <|-- gerente

usuario -up-> (login)

admin -up-> (cadastra usuarios)
admin -up-> (cadastra salas)
(cadastra usuarios) .up.> (login) : include
(cadastra salas) .up.> (login) : include

gerente -up-> (cadastra produtos)
gerente -up-> (distribui produtos)
(cadastra produtos) .up.> (login) : include
(distribui produtos) .up.> (login) : include

secretaria -up-> (cadastra paciente)
secretaria -up-> (agenda consulta)
(cadastra paciente) .up.> (login) : include
(agenda consulta) .up.> (login) : include

medico -up-> (realiza consulta) 
medico -up-> (usa produtos)
(realiza consulta) .up.> (login) : include
(usa produtos) .up.> (login) : include

@enduml
