@startuml
title Visão Arquitetural

package "Aplicação" {
  left to right direction

  package "Cliente" {
    [Cliente web] as web
  }

  package "Servidor" {
    [Router] as r
    [Controller] as c
    [Repository] as rp
    [Service] as s
    [Middleware] as md
    [PrismaSchema] as ps
    [Banco de dados] as db
  }

  web --> r
  r --> c
  c --> rp
  c --> s
  r --> md
  rp --> ps
  ps --> db
}
@enduml
