@startuml
skinparam participantPadding 20
skinparam boxPadding 10

title "Abre consulta"

box #LightBlue
participant "Api" as A
participant "AppointmentRouter" as R
participant "UpdateAppointmentController" as C
participant "DatabaseAppointmentRepositoryStrategy" as RP
participant "PrismaSchema" as PS
database "Banco de Dados" as DB

A -> R: PUT /appointments/:id
activate R
R -> C: updateAppointment()
activate C
C -> RP: getById()
activate RP
RP -> PS: findUnique()
activate PS
PS -> DB: SELECT ... FROM ... WHERE ...
activate DB
DB -> PS: Retorna o appointment
deactivate DB
PS -> RP: Retorna o appointment
deactivate PS
RP -> C: Retorna o appointment
deactivate RP

alt Caso appointment exista
    C -> RP: update()
    activate RP
    RP -> PS: update()
    activate PS
    PS -> DB: UPDATE ... SET ... WHERE ...
    activate DB
    DB -> PS: Retorna o appointment atualizado
    deactivate DB
    PS -> RP: Retorna o appointment atualizado
    deactivate PS



    RP -> C: Retorna o appointment atualizado
    deactivate RP
end

'Retorna resposta'
C -> R: Retorna Resposta
deactivate C
R -> A: Retorna Resposta
deactivate R

note left of A
    Requisição que virá
    do front (View)
    e baterá na rota
    '/appointments'.
end note

note left of A
    Diagrama feito partindo de que 
    o status está como SCHEDULE
end note

@enduml
