@startuml
skinparam participantPadding 20
skinparam boxPadding 10

title "Abre consulta"

box #LightBlue
participant "Api" as A
participant "AppointmentRouter" as R
participant "UpdateAppointmentController" as C
participant "DatabaseAppointmentRepositoryStrategy" as RP
database "Banco de Dados" as DB

A -> R: requisição put para alterar estado da consulta
activate R
R -> C: Chama updateAppointment
activate C
C -> RP: Solicita o appointment
activate RP
RP -> DB: busca appointment pelo id
activate DB
DB -> RP: retornar o appointment
deactivate DB
RP -> C: retornou o appointment
deactivate RP

alt Caso appointment exista

    C -> RP: Faz update
    activate RP
    RP -> DB: Faz update
    activate DB
    DB -> RP: retornar o appointment atualizado
    deactivate DB
    RP -> C: retornou o appointment atualizado
    deactivate RP
end

'Retorna resposta'
C -> R: Retorna Resposta
deactivate C
R -> A: Retorna Resposta
deactivate R

note left of A
    Requisição que virá
    do front (View)
    e baterá na rota
    '/appointments'.
end note

note left of A
    Diagrama feito partindo de que 
    o status está como SCHEDULE
end note

@enduml
