@startuml
skinparam participantPadding 20
skinparam boxPadding 10

title "Agenda consulta com paciente"

box #LightBlue
participant "Api" as A
participant "AppointmentRouter" as R
participant "CreateAppointmentController" as C
participant "UserRepositoryStrategy" as URP
participant "PatientsRepositoryStrategy" as PRP
participant "RoomRepositoryStrategy" as RRP
participant "AppointmentRepositoryStrategy" as ARP
participant "PrismaSchema" as PS
database "Banco de Dados" as DB

A -> R: POST /appointments
activate R
R -> C: createAppointment()
activate C

C -> URP: getById()
activate URP
URP -> PS: findUnique()
activate PS
PS -> DB: SELECT ... FROM ... WHERE ...
activate DB
DB -> PS: Retorna o usuario
deactivate DB
PS -> URP: Retorna o usuario
deactivate PS
URP -> C: Retorna o usuario
deactivate URP

alt se usuario existe e ROLE do usuario é médico
    C -> PRP: getById()
    activate PRP
    PRP -> PS: findUnique()
    activate PS
    PS -> DB: SELECT ... FROM ... WHERE ...
    activate DB
    DB -> PS: Retorna o paciente
    deactivate DB
    PS -> PRP: Retorna o paciente
    deactivate PS
    PRP -> C: Retorna o paciente
    deactivate PRP

    alt se encontrou paciente
        C -> RRP: getById()
        activate RRP
        RRP -> PS: findUnique()
        activate PS
        PS -> DB: SELECT ... FROM ... WHERE ...
        activate DB
        DB -> PS: Retorna a sala
        deactivate DB
        PS -> RRP: Retorna a sala
        deactivate PS
        RRP -> C: Retorna a sala
        deactivate RRP

        alt se existe sala disponivel
            C -> ARP: create()
            activate ARP
            ARP -> PS: create()
            activate PS
            PS -> DB: INSERT INTO ... VALUES ...
            activate DB
            DB -> PS: Retorna a consulta
            deactivate DB
            PS -> ARP: Retorna a consulta
            deactivate PS
            ARP -> C: Retorna a consulta
            deactivate ARP
        end
    end
end


'Retorna resposta'
C -> R: Retorna Resposta
deactivate C
R -> A: Retorna Resposta
deactivate R

note left of A
    Requisição que virá
    do front (View)
    e baterá na rota
    '/appointments'.
end note


@enduml
