@startuml
skinparam participantPadding 20
skinparam boxPadding 10

title "Agenda consulta com paciente" 

box #LightBlue
participant "Api" as A
participant "AppointmentRouter" as R
participant "CreateAppointmentController" as C
participant "UserRepositoryStrategy" as URP
participant "PatientsRepositoryStrategy" as PRP
participant "AppointmentRepositoryStrategy" as ARP
database "Banco de Dados" as DB

A -> R: requisição post para criar consulta
activate R
R -> C: Chama createAppointment
activate C

C -> URP: Solicita o usuario
activate URP
URP -> DB: busca usuario pelo id
activate DB
DB -> URP: retornar o usuario
deactivate DB
URP -> C: retornou o usuario
deactivate URP

alt se ROLE do usuario é médico
    C -> PRP: Solicita o paciente
    activate PRP
    PRP -> DB: busca paciente pelo id
    activate DB
    DB -> PRP: retornar o paciente
    deactivate DB
    PRP -> C: retornou o paciente
    deactivate PRP

    alt se encontrou paciente
        C -> ARP: Cria a consulta
        activate ARP
        ARP -> DB: Cria a consulta
        activate DB
        DB -> ARP: retornar a consulta
        deactivate DB
        ARP -> C: retornou a consulta
        deactivate ARP
    end
end


'Retorna resposta'
C -> R: Retorna Resposta
deactivate C
R -> A: Retorna Resposta
deactivate R

note left of A
    Requisição que virá
    do front (View)
    e baterá na rota
    '/appointments'.
end note


@enduml