
@startuml
skinparam participantPadding 20
skinparam boxPadding 10

title "Cadastra novos produtos no estoque" 

box #LightBlue

participant "Api" as A
participant "ProductRouter" as R
participant "CreateProductController" as C
participant "ProductRepositoryStrategy" as PRP
participant "PrismaSchema" as PS
database "Banco de Dados" as DB

A -> R: POST /products
activate R
R -> C: createProduct()
activate C
C -> PRP: create()
activate PRP
PRP -> PS: create()
activate PS
PS -> DB: INSERT INTO ... VALUES ...
activate DB
DB -> PS: Retorna o produto
deactivate DB
PS -> PRP: Retorna o produto
deactivate PS
PRP -> C: Retorna o produto
deactivate PRP
C -> R: Retorna Resposta
deactivate C
R -> A: Retorna Resposta
deactivate R

@enduml
