@startuml
skinparam participantPadding 20
skinparam boxPadding 10

title "Cadastra novos produtos no estoque" 

box #LightBlue

participant "Api" as A
participant "ProductRouter" as R
participant "CreateProductController" as C
participant "ProductRepositoryStrategy" as PRP
database "Banco de Dados" as DB

A -> R: requisição post para criar produto
activate R
R -> C: Chama createProduct
activate C
C -> PRP: Cria um produto
activate PRP
PRP -> DB: Cria um produto
activate DB
DB -> PRP: retornar o produto
deactivate DB
PRP -> C: retornou o produto
deactivate PRP
C -> R: Retorna Resposta
deactivate C
R -> A: Retorna Resposta
deactivate R

@enduml